// <auto-generated />
using System;
using Console.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Console.Migrations
{
    [DbContext(typeof(ScoreBoardContext))]
    [Migration("20210413101126_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Console.Models.Score", b =>
                {
                    b.Property<Guid>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<Guid?>("ScoreBoardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScoreId");

                    b.HasIndex("ScoreBoardId");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("Console.Models.ScoreBoard", b =>
                {
                    b.Property<Guid>("ScoreBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ScoreBoardId");

                    b.ToTable("ScoreBoards");
                });

            modelBuilder.Entity("Console.Models.Score", b =>
                {
                    b.HasOne("Console.Models.ScoreBoard", "ScoreBoard")
                        .WithMany("Scores")
                        .HasForeignKey("ScoreBoardId");

                    b.Navigation("ScoreBoard");
                });

            modelBuilder.Entity("Console.Models.ScoreBoard", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
